services:
  database:
    image: mysql:8.0
    container_name: spotify_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spotify
    ports:
      - "3306:3306"
    volumes:
      - ./spotify_data:/var/lib/mysql
      - ./spotify.cnf:/etc/mysql/conf.d/spotify.cnf


volumes:
  spotify_data:
